builds:
- id: ruuviscan
  binary: ruuviscan
  env:
    - CGO_ENABLED=1
  targets:
    - "darwin_amd64"
    - "darwin_arm64"
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
checksum:
  algorithm: sha256
  name_template: "darwin_checksums.txt"
