builds:
- id: ruuviscan
  binary: ruuviscan
  env:
    - CGO_ENABLED=0
  targets:
    - "linux_amd64"
    - "linux_arm64"
    - "linux_arm"
    - "windows_amd64"
    - "windows_arm64"
checksum:
  algorithm: sha256
  name_template: "checksums.txt"
